/*
Imperial Defense Network 
Database Creation Script
HG Locklear
Spring Semester 2022
*/

DROP DATABASE IF EXISTS imperial_defense;
CREATE DATABASE imperial_defense;
USE imperial_defense;

CREATE TABLE AntiVirus(
SName VARCHAR(25),
Manufacturer VARCHAR(25),
CurrentVersion VARCHAR(25),
PreviousVersion VARCHAR(25),
ReviseDate DATE,
CONSTRAINT PK_AVIRUS PRIMARY KEY(SName)
);

CREATE TABLE Firewall(
IDNumber VARCHAR(25),
SystemName VARCHAR(25),
Filter VARCHAR(25) NOT NULL DEFAULT 'Packet',
CONSTRAINT PK_FIRE PRIMARY KEY(IDNumber)
);

CREATE TABLE Subnet(
IDNumber VARCHAR(25),
BitMask CHAR(14),
Protocol ENUM('IPv4','IPv6') NOT NULL,
DHCProtocol ENUM('Alpha','Beta','Gamma') NOT NULL,
CONSTRAINT PK_SUB PRIMARY KEY(IDNumber)
);

CREATE TABLE IntrusionSystem(
SystemID VARCHAR(25),
SystemType ENUM("Network",'Host-Based') NOT NULL,
Detection ENUM('Signature','Anomaly') NOT NULL,
CONSTRAINT PK_INTRUSION PRIMARY KEY(SystemID)
);

CREATE TABLE Site(
SiteName VARCHAR(25),
SiteID VARCHAR(25),
SiteStatus ENUM('ONLINE','OFFLINE') NOT NULL,
XCoord INT,
YCoord INT,
CONSTRAINT PK_SITE PRIMARY KEY(SiteID),
CONSTRAINT UK_SITE UNIQUE KEY(SiteName)
);

CREATE TABLE Network(
NetName VARCHAR(25),
NetType ENUM('DATA','COMM','VIDEO') NOT NULL,
Bandwidth DECIMAL(10,2) NOT NULL,
OptimumBW DECIMAL(10,2) GENERATED ALWAYS AS(Bandwidth * 0.85) STORED,
MaxBW DECIMAL(10,2) GENERATED ALWAYS AS(Bandwidth * 1.25) STORED,
MinBW DECIMAL(10,2) GENERATED ALWAYS AS(Bandwidth * 0.45) STORED,
CSwitched BOOLEAN NOT NULL,
NetStatus ENUM('ONLINE','OFFLINE') NOT NULL,
CONSTRAINT PK_NET PRIMARY KEY(NetName)
);

CREATE TABLE Router(
RID VARCHAR(10),
RType ENUM('Interior','Exterior','Border') NOT NULL,
RouteFinding ENUM('Static','Dynamic') NOT NULL,
Connectivity ENUM('Edge','Backbone','Port Forwarding') NOT NULL,
AssignedTo VARCHAR(25),
CONSTRAINT PK_RTR PRIMARY KEY(RID)
);

CREATE TABLE Switch(
SID VARCHAR(10),
EntryPort INT NOT NULL,
ExitPort INT NOT NULL,
Stackable BOOLEAN NOT NULL,
PoE BOOLEAN NOT NULL,
AssignedTo VARCHAR(25),
CONSTRAINT PK_SWITCH PRIMARY KEY(SID),
CONSTRAINT UK_SWITCH1 UNIQUE KEY(EntryPort),
CONSTRAINT UK_SWITCH2 UNIQUE KEY(ExitPort)
);

CREATE TABLE Hub(
HID VARCHAR(10),
Ports INT,
EntryPort INT NOT NULL,
ExitPort INT NOT NULL,
AssignedTo VARCHAR(25),
CONSTRAINT PK_Hub PRIMARY KEY(HID),
CONSTRAINT UK_HUB1 UNIQUE KEY(EntryPort),
CONSTRAINT UK_HUB2 UNIQUE KEY(ExitPort)
);

CREATE TABLE Repeater(
RPID VARCHAR(10),
Ports INT,
EntryPort INT NOT NULL,
ExitPort INT NOT NULL,
AssignedTo VARCHAR(25),
CONSTRAINT PK_RP PRIMARY KEY(RPID),
CONSTRAINT UK_RP1 UNIQUE KEY(EntryPort),
CONSTRAINT UK_RP2 UNIQUE KEY(ExitPort)
);

CREATE TABLE Widget(
WID VARCHAR(25),
WType ENUM('Terminal','Pad','Device') NOT NULL,
AssignedTo VARCHAR(25),
Location VARCHAR(25) NOT NULL DEFAULT 'Unknown',
AccessCode VARCHAR(25) NOT NULL DEFAULT 'Pace',
Secure BOOLEAN NOT NULL DEFAULT false,
User JSON,
CONSTRAINT PK_WIDGET PRIMARY KEY(WID)
);

SELECT 'DATABASE BUILD COMPLETE' AS MSG;



